name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this entire form to ensure your bug can be properly reproduced!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of Unicord are you running? (Check under Apps in Settings)
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Windows version
      description: Which Windows version did you experience this bug on?
      multiple: true
      options:
        - "Windows 11 Insider Build (xxxxx)"
        - "Windows 11 (22000)"
        - "Windows 10 Insider Build (xxxxx)"
        - "Windows 10 May 2021 Update (19043)"
        - "Windows 10 October 2020 Update (19042)"
        - "Windows 10 May 2020 Update (19041)"
        - "Windows 10 November 2019 Update (18363)"
        - "Windows 10 May 2019 Update (18362)"
        - "Windows 10 October 2018 Update (17763)"
        - "Windows 10 April 2018 Update (17134)"
        - "Windows 10 Fall Creators Update (16299)"
        - "Windows 10 Creators Update (15063)"
  - type: dropdown
    id: platform
    attributes:
      label: What platform are you seeing the problem on?
      multiple: false
      options:
        - Desktop
        - Mobile
        - Xbox
        - IoT
        - Hub