// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190620.2

#pragma once
#include "winrt/Unicord.Universal.Voice.Background.h"
#include "winrt/Windows.ApplicationModel.Background.h"
namespace winrt::Unicord::Universal::Voice::Background::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) ServiceBackgroundTask_base : implements<D, Unicord::Universal::Voice::Background::ServiceBackgroundTask, Windows::ApplicationModel::Background::IBackgroundTask, I...>
    {
        using base_type = ServiceBackgroundTask_base;
        using class_type = Unicord::Universal::Voice::Background::ServiceBackgroundTask;
        using implements_type = typename ServiceBackgroundTask_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"Unicord.Universal.Voice.Background.ServiceBackgroundTask";
        }
    };
}
namespace winrt::Unicord::Universal::Voice::Background::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct __declspec(empty_bases) ServiceBackgroundTaskT : implements<D, Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = Unicord::Universal::Voice::Background::ServiceBackgroundTask;

        hstring GetRuntimeClassName() const
        {
            return L"Unicord.Universal.Voice.Background.ServiceBackgroundTask";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_SERVICEBACKGROUNDTASK_XAML_G_H) || __has_include("Background.ServiceBackgroundTask.xaml.g.h")
#include "Background.ServiceBackgroundTask.xaml.g.h"
#else

namespace winrt::Unicord::Universal::Voice::Background::implementation
{
    template <typename D, typename... I>
    using ServiceBackgroundTaskT = ServiceBackgroundTask_base<D, I...>;
}

#endif
