// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190605.7

#pragma once
#include "winrt/Unicord.Universal.Voice.h"
#include "winrt/Windows.Foundation.h"
namespace winrt::Unicord::Universal::Voice::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) VideoEventArgs_base : implements<D, Unicord::Universal::Voice::VideoEventArgs, Windows::Foundation::IClosable, I...>
    {
        using base_type = VideoEventArgs_base;
        using class_type = Unicord::Universal::Voice::VideoEventArgs;
        using implements_type = typename VideoEventArgs_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"Unicord.Universal.Voice.VideoEventArgs";
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_VIDEOEVENTARGS_XAML_G_H) || __has_include("VideoEventArgs.xaml.g.h")
#include "VideoEventArgs.xaml.g.h"
#else

namespace winrt::Unicord::Universal::Voice::implementation
{
    template <typename D, typename... I>
    using VideoEventArgsT = VideoEventArgs_base<D, I...>;
}

#endif
