import "VoiceClientOptions.idl";
import "VoiceOutputStream.idl";

namespace Unicord.Universal.Voice
{ 
    [default_interface]
	runtimeclass VoiceClient : Windows.Foundation.IClosable
    {
		static String OpusVersion{ get; };
		static String SodiumVersion{ get; };

		VoiceClient(VoiceClientOptions options);
		UInt32 WebSocketPing{ get; };

		Windows.Foundation.IAsyncAction ConnectAsync();
		Windows.Storage.Streams.IOutputStream GetOutputStream();
	};
}
