// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190620.2

void* winrt_make_Unicord_Universal_Voice_VoiceClient()
{
    return winrt::detach_abi(winrt::make<winrt::Unicord::Universal::Voice::factory_implementation::VoiceClient>());
}
namespace winrt::Unicord::Universal::Voice
{
    VoiceClient::VoiceClient(Unicord::Universal::Voice::VoiceClientOptions const& options) :
        VoiceClient(make<Unicord::Universal::Voice::implementation::VoiceClient>(options))
    {
    }
    hstring VoiceClient::OpusVersion()
    {
        return Unicord::Universal::Voice::implementation::VoiceClient::OpusVersion();
    }
    hstring VoiceClient::SodiumVersion()
    {
        return Unicord::Universal::Voice::implementation::VoiceClient::SodiumVersion();
    }
}
