// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190620.2

void* winrt_make_Unicord_Universal_Voice_VoiceClientOptions()
{
    return winrt::detach_abi(winrt::make<winrt::Unicord::Universal::Voice::factory_implementation::VoiceClientOptions>());
}
namespace winrt::Unicord::Universal::Voice
{
    VoiceClientOptions::VoiceClientOptions() :
        VoiceClientOptions(make<Unicord::Universal::Voice::implementation::VoiceClientOptions>())
    {
    }
}
