// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190620.2

void* winrt_make_Unicord_Universal_Voice_VoiceOutputStream()
{
    return winrt::detach_abi(winrt::make<winrt::Unicord::Universal::Voice::factory_implementation::VoiceOutputStream>());
}
namespace winrt::Unicord::Universal::Voice
{
    VoiceOutputStream::VoiceOutputStream(Unicord::Universal::Voice::VoiceClient const& client) :
        VoiceOutputStream(make<Unicord::Universal::Voice::implementation::VoiceOutputStream>(client))
    {
    }
}
