namespace Unicord.Universal.Voice.Background
{
    enum VoiceServiceRequest
    {
        RequestSucceeded,
        RequestFailed,

        StateRequest,
        NotifyIncomingCallRequest,
        NotifyCallEndRequest,
        GuildConnectRequest,
        CallConnectRequest,
        GuildMoveRequest,
        DisconnectRequest,
        MuteRequest,
        DeafenRequest,
        SettingsUpdate
    };

    enum VoiceServiceState
    {
        Connected,
        ReadyToConnect
    };
}