import "NoiseSuppressionLevel.idl";

namespace Unicord.Universal.Voice
{
    runtimeclass VoiceClientOptions
    {
        VoiceClientOptions();
        String Token;
        String SessionId;
        String Endpoint;
        UInt64 GuildId;
        UInt64 ChannelId;
        UInt64 CurrentUserId;
        String PreferredPlaybackDevice;
        String PreferredRecordingDevice;
        Unicord.Universal.Voice.NoiseSuppressionLevel SuppressionLevel;
        Boolean EchoCancellation;
        Boolean VoiceActivity;
        Boolean AutomaticGainControl;
    };
}