// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190620.2

#pragma once
#include "winrt/Unicord.Universal.Voice.h"
namespace winrt::Unicord::Universal::Voice::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) VoiceClientOptions_base : implements<D, Unicord::Universal::Voice::VoiceClientOptions, I...>
    {
        using base_type = VoiceClientOptions_base;
        using class_type = Unicord::Universal::Voice::VoiceClientOptions;
        using implements_type = typename VoiceClientOptions_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"Unicord.Universal.Voice.VoiceClientOptions";
        }
    };
}
namespace winrt::Unicord::Universal::Voice::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct __declspec(empty_bases) VoiceClientOptionsT : implements<D, Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = Unicord::Universal::Voice::VoiceClientOptions;

        hstring GetRuntimeClassName() const
        {
            return L"Unicord.Universal.Voice.VoiceClientOptions";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_VOICECLIENTOPTIONS_XAML_G_H) || __has_include("VoiceClientOptions.xaml.g.h")
#include "VoiceClientOptions.xaml.g.h"
#else

namespace winrt::Unicord::Universal::Voice::implementation
{
    template <typename D, typename... I>
    using VoiceClientOptionsT = VoiceClientOptions_base<D, I...>;
}

#endif
